app1/urls.py
from app1.views import *
from django.urls import path
app_name='something'
urlpatterns=[
    path('yeswanth/',yeswanth,name='yeswanth'),
]

app2/urls.py
from app2.views import *
from django.urls import path
app_name='nothing'
urlpatterns=[
    path('respose/',response,name='response'),
]

project13/urls.py
from django.contrib import admin
from django.urls import path,include
import app1
import app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def yeswanth(request):
    return render(request,'yeswanth.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def response(request):
    return render(request,'response.html')

templates/response.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>
            chaduvkondi firstuu........
        </h1>
        <a href="{% url 'something:yeswanth' %}"><h1>yeswanth request</h1></a>
    </center>
</body>
</html>

templates/yeswanth.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>Hi i am yeswanth i want a girl for stressboosting</h1>
        <a href="{% url 'nothing:response' %}"><h1>To get response click here</h1></a>
    </center>
</body>
</html>